### ISSUE TITLE
您好，我安装完后有这个错误，可以帮我看一下吗

### ISSUE THREAD

**Issue by PANDAZZ1108** [wushuo894/EmbyPinyin#1]
日志是这样的，emby里面测试通知发送也是失败的，我应该怎么调整
stdout: [2024-09-02 04:01:25] [INFO] com.emby.Main: Webhooks = 
stderr: [2024-09-02 04:01:25] [ERROR] com.emby.Main: Cannot invoke "com.google.gson.JsonObject.get(String)" because "jsonObject" is null
stderr: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.get(String)" because "jsonObject" is null
stderr: 	at com.emby.Main.lambda$main$3(Main.java:75)
stderr: 	at cn.hutool.http.server.handler.ActionHandler.handle(ActionHandler.java:44)
stderr: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
stderr: 	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
stderr: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
stderr: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:733)
stderr: 	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
stderr: 	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:700)
stderr: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
stderr: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
stderr: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by wushuo894** [comment]
Webhooks的内容为空

你应该是配置的不对
检查一下emby的地址和key

**Comment by wushuo894** [comment]
![image](https://github.com/user-attachments/assets/6b6cd78f-20d6-4a06-a2cc-bce39ffa9106)
你是不是没改请求内容类型

**Comment by PANDAZZ1108** [comment]
请求内容就是这个，我这里在重新装一下

**Comment by PANDAZZ1108** [comment]
![image](https://github.com/user-attachments/assets/0ab9d07a-134e-45b8-bc3f-746349b38d18)
![image](https://github.com/user-attachments/assets/7c834255-0a30-49ae-8be1-3647c9fab960)
![image](https://github.com/user-attachments/assets/27b43531-d2cf-4f54-a993-3756310d6c37)

这是我的设置，还有日志

**Comment by PANDAZZ1108** [comment]
发送通知还是 错误

**Comment by wushuo894** [comment]
你是不是发送的测试通知

**Comment by PANDAZZ1108** [comment]
是的。。

**Comment by wushuo894** [comment]
你实际添加一个电影试试

**Comment by wushuo894** [comment]
测试通知不是这么玩的

**Comment by PANDAZZ1108** [comment]
还有，我应该怎么让他开始修改类标题，目前我库中还是没有修改的状态。

**Comment by wushuo894** [comment]
> 还有，我应该怎么让他开始修改类标题，目前我库中还是没有修改的状态。

没有理解你的意思

**Comment by wushuo894** [comment]
> 还有，我应该怎么让他开始修改类标题，目前我库中还是没有修改的状态。

不会影响原有的标题，修改的是一个隐藏的排序字段

**Comment by PANDAZZ1108** [comment]
我是想问，我不知道它是否在正常运行，我得媒体库现在还是汉字排序的，怎么弄才能让他全量修改一遍呀

**Comment by wushuo894** [comment]
> 我是想问，我不知道它是否在正常运行，我得媒体库现在还是汉字排序的，怎么弄才能让他全量修改一遍呀

将RUN设置为TRUE，ITEM设置为-
启动一分钟后他会自动开始

**Comment by PANDAZZ1108** [comment]
不知道哪里出了问题，还是没反应，明天再说吧，先休息了，谢谢你

**Comment by PANDAZZ1108** [comment]
![image](https://github.com/user-attachments/assets/29af8715-3c41-4f5a-88e9-b35caea89a3b)
您好，现在的问题是，在使用pinyin插件之前，emby已经添加的电影，貌似不会修改或者只会修改一个部分元数据中的类标题。之后大批量添加的电影，会漏掉一些没有修改元数据中的类标题。遇到这种情况，我尝试手动修改其余插件没有修改的元数据，全部改完后，排序那里还是会显示汉字。我只能重新扫库

**Comment by wushuo894** [comment]
> ![image](https://private-user-images.githubusercontent.com/104128997/364718512-29af8715-3c41-4f5a-88e9-b35caea89a3b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzI3NTIsIm5iZiI6MTcyNTUzMjQ1MiwicGF0aCI6Ii8xMDQxMjg5OTcvMzY0NzE4NTEyLTI5YWY4NzE1LTNjNDEtNGY1YS04OGU5LWIzNWNhZWE4OWEzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwNVQxMDM0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDI4YTA3ZTlhNjQ0YzljZjM2ZWQzNzhjMzI1Zjg0ODNjMWEyYjk4Y2RkZTM2YWZlNjQwMjk0NGVjZGQyNGU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oxeToLyyV6DyTEDANdK3Ah2Bh_on4hV8AZVJc7fNLRs) 您好，现在的问题是，在使用pinyin插件之前，emby已经添加的电影，貌似不会修改或者只会修改一个部分元数据中的类标题。之后大批量添加的电影，会漏掉一些没有修改元数据中的类标题。遇到这种情况，我尝试手动修改其余插件没有修改的元数据，全部改完后，排序那里还是会显示汉字。我只能重新扫库

将RUN设置为TRUE，ITEM设置为-
启动一分钟后他会自动开始处理所有的电影

**Comment by wushuo894** [comment]
解决了吗？
